version: 0.2

phases:
  install: 
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Package & Dependicies are getting installed"
      - npm -f install
      - npm run build
      - echo "Packages have been installed"
      - echon "Storing Build Artifact to the Location"
  post_build:
    commands:
     - echo Configuring nginx    
artifacts:
  files:
   - '**/*'
  name: mydemo-app